### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [Satyakb9/f1-3-c2p1-colmar-academy#6]
**Summary Grade: Satisfactory**

Great job! Your files are organized, your code is well structured, and you did a good job at following the client specification and making your site super user friendly. Moreover, your code is generally simple, clean and easy to follow overall so definitely make sure to keep that up!

I have made a few comments about your code. You did a great job at making your page responsive. When I change the size of the browser, the elements on the screen adjust accordingly. I did notice, however, that the images on the screen seem to stretch out when I change the browser width, so I would double check how you are adjusting the width of those images when the browser width changes. 

Moreover, your HTML is very nicely structured and easy to follow, and you made sure to comment your code well. You should also make sure to comment your main stylings in your CSS, since CSS can get especially confusing after a while of not looking at it. Here is a quick refresher on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/29794863-d91dc584-8c17-11e7-85aa-ef3e9303f2cb.png">

Overall, I really like the look and feel of the site! It's clear that you have an eye for web design. Overall, you followed all of the directions of the specifications, and did an excellent job. It is evident that you have been growing as a developer, so definitely make sure to keep up the momentum!

As a further challenge, see if you can incorporate a dropdown menu system in your website! This can be tricky and may require outside research for you to understand, but it is certainly a cool feature to have. I would recommend this resource to get you started:

https://www.w3schools.com/css/css_dropdowns.asp

**Comment by Satyakb9** [comment]
Thank you for the detailed feedback, the encouraging words and for reviewing so quickly! I will definitely look into the further challenge.
